//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/InputSystem/InputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystem"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""b55fa7c5-ebf6-4b0d-a894-4f3b2444c711"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""5722bcbf-a42e-4cb3-8764-37cfd473b7a9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MovementWASD"",
                    ""type"": ""Value"",
                    ""id"": ""9a177cc9-bf50-4781-8a22-63f3512276c7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""76288315-406e-4b99-99e9-b3db5fd7026d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Power 1"",
                    ""type"": ""Button"",
                    ""id"": ""0489247b-3293-4956-a7e8-d829362989e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Power 2"",
                    ""type"": ""Button"",
                    ""id"": ""fb503a61-f581-49e6-a4e7-440213ea4478"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""a4e57bcc-da34-4a5b-9733-1600d2386b9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rewind"",
                    ""type"": ""Button"",
                    ""id"": ""a7568a94-888e-4fb3-b1bd-2fd184fad138"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""20816ea0-c44b-4948-9d20-f2e73142cf87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""53ac953d-6787-4ef6-a0a0-0c2c259c05dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActiveObjectOne"",
                    ""type"": ""Button"",
                    ""id"": ""242509c3-96ab-4e2e-a1d1-6e8cc1f85010"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActiveObjectTwo"",
                    ""type"": ""Button"",
                    ""id"": ""616b2cc6-c010-4621-b499-e712a1adc4a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActiveObjectThree"",
                    ""type"": ""Button"",
                    ""id"": ""cf383ffd-bcab-46d3-9b59-8fd484a66b35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActiveObjectFour"",
                    ""type"": ""Button"",
                    ""id"": ""5acc57da-18a5-403c-8430-3d99c5525178"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""92ab5cbe-4a14-4d7c-887b-712066d0e94d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7f591edd-1f2d-4b9d-b717-622dfec92e8e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7d15e64d-a547-436e-945a-9167e1c63449"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""42b624e4-b604-4bb9-8b22-ab83a254f6a6"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e365496e-1304-4af3-b5a5-f2f5fa5288e5"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""bb652d7e-2464-4bf5-b52e-d88cf3e8c461"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae6944d6-3bf8-4958-8254-e7757b0f8733"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Power 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92afaad9-772b-4b00-92c9-381f76bcf9a1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Power 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7022fc44-646f-48ed-9fe6-d91259b74ff1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b744433e-a885-4a02-b591-d89fbed928a0"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rewind"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5eb25bd7-1c3f-4b5b-8b7d-7faf22547761"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40859486-ab60-4492-82ec-ad8bed849d9f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37d75f8d-f2f1-4ecc-8e39-67e44e5b51a8"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveObjectOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a135981-acd2-470b-a580-8e7dfd3cce49"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveObjectTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6d552d0-361b-4ebd-bc8b-564cdeb72a36"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveObjectThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2009579d-3e1b-4f60-9874-1389723b04f3"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveObjectFour"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ca906015-6d48-4e21-a6f3-a32d7116dbe2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementWASD"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2a512890-4f42-49f5-b0a6-a8a770b0a5f1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementWASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""731bfbe7-ad2b-4a9b-9a03-7555d9e3b20b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementWASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f9dfba7e-5ba8-46f0-8aef-873450f314f6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementWASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""29e5f8a2-8841-4245-8559-78f41f490cfa"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementWASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_MovementWASD = m_Player.FindAction("MovementWASD", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_Power1 = m_Player.FindAction("Power 1", throwIfNotFound: true);
        m_Player_Power2 = m_Player.FindAction("Power 2", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_Rewind = m_Player.FindAction("Rewind", throwIfNotFound: true);
        m_Player_Interaction = m_Player.FindAction("Interaction", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_ActiveObjectOne = m_Player.FindAction("ActiveObjectOne", throwIfNotFound: true);
        m_Player_ActiveObjectTwo = m_Player.FindAction("ActiveObjectTwo", throwIfNotFound: true);
        m_Player_ActiveObjectThree = m_Player.FindAction("ActiveObjectThree", throwIfNotFound: true);
        m_Player_ActiveObjectFour = m_Player.FindAction("ActiveObjectFour", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_MovementWASD;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_Power1;
    private readonly InputAction m_Player_Power2;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_Rewind;
    private readonly InputAction m_Player_Interaction;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_ActiveObjectOne;
    private readonly InputAction m_Player_ActiveObjectTwo;
    private readonly InputAction m_Player_ActiveObjectThree;
    private readonly InputAction m_Player_ActiveObjectFour;
    public struct PlayerActions
    {
        private @InputSystem m_Wrapper;
        public PlayerActions(@InputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @MovementWASD => m_Wrapper.m_Player_MovementWASD;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @Power1 => m_Wrapper.m_Player_Power1;
        public InputAction @Power2 => m_Wrapper.m_Player_Power2;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @Rewind => m_Wrapper.m_Player_Rewind;
        public InputAction @Interaction => m_Wrapper.m_Player_Interaction;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @ActiveObjectOne => m_Wrapper.m_Player_ActiveObjectOne;
        public InputAction @ActiveObjectTwo => m_Wrapper.m_Player_ActiveObjectTwo;
        public InputAction @ActiveObjectThree => m_Wrapper.m_Player_ActiveObjectThree;
        public InputAction @ActiveObjectFour => m_Wrapper.m_Player_ActiveObjectFour;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @MovementWASD.started += instance.OnMovementWASD;
            @MovementWASD.performed += instance.OnMovementWASD;
            @MovementWASD.canceled += instance.OnMovementWASD;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Power1.started += instance.OnPower1;
            @Power1.performed += instance.OnPower1;
            @Power1.canceled += instance.OnPower1;
            @Power2.started += instance.OnPower2;
            @Power2.performed += instance.OnPower2;
            @Power2.canceled += instance.OnPower2;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Rewind.started += instance.OnRewind;
            @Rewind.performed += instance.OnRewind;
            @Rewind.canceled += instance.OnRewind;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @ActiveObjectOne.started += instance.OnActiveObjectOne;
            @ActiveObjectOne.performed += instance.OnActiveObjectOne;
            @ActiveObjectOne.canceled += instance.OnActiveObjectOne;
            @ActiveObjectTwo.started += instance.OnActiveObjectTwo;
            @ActiveObjectTwo.performed += instance.OnActiveObjectTwo;
            @ActiveObjectTwo.canceled += instance.OnActiveObjectTwo;
            @ActiveObjectThree.started += instance.OnActiveObjectThree;
            @ActiveObjectThree.performed += instance.OnActiveObjectThree;
            @ActiveObjectThree.canceled += instance.OnActiveObjectThree;
            @ActiveObjectFour.started += instance.OnActiveObjectFour;
            @ActiveObjectFour.performed += instance.OnActiveObjectFour;
            @ActiveObjectFour.canceled += instance.OnActiveObjectFour;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @MovementWASD.started -= instance.OnMovementWASD;
            @MovementWASD.performed -= instance.OnMovementWASD;
            @MovementWASD.canceled -= instance.OnMovementWASD;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Power1.started -= instance.OnPower1;
            @Power1.performed -= instance.OnPower1;
            @Power1.canceled -= instance.OnPower1;
            @Power2.started -= instance.OnPower2;
            @Power2.performed -= instance.OnPower2;
            @Power2.canceled -= instance.OnPower2;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Rewind.started -= instance.OnRewind;
            @Rewind.performed -= instance.OnRewind;
            @Rewind.canceled -= instance.OnRewind;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @ActiveObjectOne.started -= instance.OnActiveObjectOne;
            @ActiveObjectOne.performed -= instance.OnActiveObjectOne;
            @ActiveObjectOne.canceled -= instance.OnActiveObjectOne;
            @ActiveObjectTwo.started -= instance.OnActiveObjectTwo;
            @ActiveObjectTwo.performed -= instance.OnActiveObjectTwo;
            @ActiveObjectTwo.canceled -= instance.OnActiveObjectTwo;
            @ActiveObjectThree.started -= instance.OnActiveObjectThree;
            @ActiveObjectThree.performed -= instance.OnActiveObjectThree;
            @ActiveObjectThree.canceled -= instance.OnActiveObjectThree;
            @ActiveObjectFour.started -= instance.OnActiveObjectFour;
            @ActiveObjectFour.performed -= instance.OnActiveObjectFour;
            @ActiveObjectFour.canceled -= instance.OnActiveObjectFour;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnMovementWASD(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnPower1(InputAction.CallbackContext context);
        void OnPower2(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnRewind(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnActiveObjectOne(InputAction.CallbackContext context);
        void OnActiveObjectTwo(InputAction.CallbackContext context);
        void OnActiveObjectThree(InputAction.CallbackContext context);
        void OnActiveObjectFour(InputAction.CallbackContext context);
    }
}
